<?php

// autoload-classmap.php @generated by Strauss

$strauss_src = dirname(__FILE__);

return array(
   'WPVibes\FormVibes\Vendor\WPVibes\ReviewReminder\Config' => $strauss_src . '/wpvibes/review-reminder/src/Config.php',
   'WPVibes\FormVibes\Vendor\WPVibes\ReviewReminder\ReviewReminder' => $strauss_src . '/wpvibes/review-reminder/src/ReviewReminder.php',
   'WPVibes\FormVibes\Vendor\WPVibes\ReviewReminder\State' => $strauss_src . '/wpvibes/review-reminder/src/State.php',
   'WPVibes\FormVibes\Vendor\WPVibes\ReviewReminder\TriggerEvaluator' => $strauss_src . '/wpvibes/review-reminder/src/TriggerEvaluator.php',
   'WPVibes\FormVibes\Vendor\WPVibes\ReviewReminder\AjaxHandler' => $strauss_src . '/wpvibes/review-reminder/src/AjaxHandler.php',
   'WPVibes\FormVibes\Vendor\WPVibes\ReviewReminder\ScreenMatcher' => $strauss_src . '/wpvibes/review-reminder/src/ScreenMatcher.php',
   'WPVibes\FormVibes\Vendor\WPVibes\ReviewReminder\ReminderRenderer' => $strauss_src . '/wpvibes/review-reminder/src/ReminderRenderer.php',
);